version: '3'
services:
 gut:
   #image: "debian:9"
   #use proxy when build:
   # - docker-compose build --build-arg http_proxy={} --build-arg https_proxy={} gut
   build: .
   volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup
   environment:
     - "container=docker"
     #- "http_proxy=http://192.168.1.101:7777"
     #- "https_proxy=http://192.168.1.101:7777"
   cap_add: [SYS_ADMIN]
   privileged: true
   tty: true
   command: /sbin/init